---
dataset_sampling: random_split
dataset_name: hugging_face_yale_ner
model_name: hugging_face_causal_lm_meta-llama/Llama-3.2-1B-Instruct
distributed_algorithm: adaptor_avg
optimizer_name: AdamW
cache_transforms: cpu
batch_size: 8
epoch: 1
use_amp: true
weight_decay: 0
learning_rate: 2e-4
model_kwargs:
  pretrained: true
  finetune_modules:
    - q_proj
    - o_proj
    - k_proj
    - v_proj
    - gate_proj
    - up_proj
    - down_proj
  # load_in_8bit: true
dataset_kwargs:
  train_files:
    - /home/cyy/NER_data/train/MIMIC3.json
    - /home/cyy/NER_data/train/MTSamples.json
    - /home/cyy/NER_data/train/UTP.json
  test_files:
    - /home/cyy/NER_data/test/MIMIC3.json
    - /home/cyy/NER_data/test/MTSamples.json
    - /home/cyy/NER_data/test/UTP.json
    - /home/cyy/NER_data/test/i2b2.json
  prompt_file: medical.txt
  no_validation: true
algorithm_kwargs:
  distribute_init_parameters: false
