---
dataset_sampling: random_split
dataset_name: hugging_face_yale_ner
model_name: hugging_face_causal_lm_meta-llama/Llama-3.2-1B-Instruct
distributed_algorithm: adaptor_avg
optimizer_name: AdamW
batch_size: 8
epoch: 1
use_amp: true
weight_decay: 0
learning_rate: 2e-4
model_kwargs:
  # load_in_8bit: true
  need_finetune: true
  pretrained: true
  finetune_modules:
    - q_proj
    - o_proj
    - k_proj
    - v_proj
    - gate_proj
    - up_proj
    - down_proj
dataset_kwargs:
  train_files: [data/a.json]
  test_files: [data/a.json]
  prompt_file: medical.txt
  no_validation: true
algorithm_kwargs:
  distribute_init_parameters: false
